version: '3'
services:
  web:
    build: .
    image: mikespub/quickstart-python
    links:
      - redis
    ports:
      - "${FLASK_PORT}:5080"
    environment:
      - FLASK_PORT=5080
      - FLASK_HOST=0.0.0.0
  redis:
    image: redis
