version: '3.6'
services:
  web:
    image: mikespub/quickstart-python
    links:
      - redis
    ports:
      - "${FLASK_PORT}:5080"
    environment:
      - FLASK_PORT=${FLASK_PORT}
      - FLASK_HOST=${FLASK_HOST}
  redis:
    image: redis
